all:
	make -C sys-headers
	make -C nativeyellow

.PHONY:clean
clean:
	make -C sys-headers clean
	make -C nativeyellow clean

.PHONY:install
install:
	make -C sys-headers install
	make -C nativeyellow install
