.PHONY: install
install:
	@mkdir -p $(NATIVECOLORS_ROOT)/srv/www/hello_hterm
	cp index.html $(NATIVECOLORS_ROOT)/srv/www/hello_hterm/
	cp hello.js $(NATIVECOLORS_ROOT)/srv/www/hello_hterm/

.PHONY: clean
clean:
