all: 
	@

.PHONY:clean
clean:
	@

.PHONY: install
install: 
	@mkdir -p $(NATIVECOLORS_ROOT)/client/srv/www/usr/www/qunit/
	cp $(NATIVECOLORS_ROOT)/client/src/packages/qunit/qunit/qunit.js $(NATIVECOLORS_ROOT)/client/srv/www/usr/www/qunit/
	cp $(NATIVECOLORS_ROOT)/client/src/packages/qunit/qunit/qunit.css $(NATIVECOLORS_ROOT)/client/srv/www/usr/www/qunit/
