.PHONY: install
install: 
	@mkdir $(NATIVECOLORS_ROOT)/srv/www/hterm
	cp -R $(NATIVECOLORS_ROOT)/usr/packages/hterm/html  $(NATIVECOLORS_ROOT)/srv/www/hterm/
	cp -R $(NATIVECOLORS_ROOT)/usr/packages/hterm/js    $(NATIVECOLORS_ROOT)/srv/www/hterm/
	cp -R $(NATIVECOLORS_ROOT)/usr/packages/hterm/css   $(NATIVECOLORS_ROOT)/srv/www/hterm/
	cp -R $(NATIVECOLORS_ROOT)/usr/packages/hterm/audio $(NATIVECOLORS_ROOT)/srv/www/
