all: 
	@

.PHONY:clean
clean:
	@

.PHONY: install
install: 
	@mkdir -p $(NATIVECOLORS_ROOT)/client/srv/www/usr/www/filer.js/
	cp $(NATIVECOLORS_ROOT)/client/src/packages/filer.js/src/*.js $(NATIVECOLORS_ROOT)/client/srv/www/usr/www/filer.js/
