all: 
	@

.PHONY:clean
clean:
	@

.PHONY: install
install: 
	@mkdir -p $(NATIVECOLORS_ROOT)/client/srv/www/usr/www/waituntilexists.js/
	cp $(NATIVECOLORS_ROOT)/client/src/packages/waituntilexists.js/*.js $(NATIVECOLORS_ROOT)/client/srv/www/usr/www/waituntilexists.js/
