all: 
	@

.PHONY:clean
clean:
	@

.PHONY: install
install: 
	@mkdir -p $(NATIVECOLORS_ROOT)/client/srv/www/usr/www/jquery.fs.js/
	cp $(NATIVECOLORS_ROOT)/client/src/packages/jquery.fs.js/jquery.fs.js $(NATIVECOLORS_ROOT)/client/srv/www/usr/www/jquery.fs.js/
	cp $(NATIVECOLORS_ROOT)/client/src/packages/jquery.fs.js/jquery.fs.min.js $(NATIVECOLORS_ROOT)/client/srv/www/usr/www/jquery.fs.js/
